name: nikes
description: A sample Chrome packaged application
dependencies:
  browser: any
  chrome: any
  paper_elements: ">=0.5.0 <0.6.0"
  core_elements: ">=0.4.0+2 <0.5.0"
dev_dependencies:
  grinder: '>=0.6.0 < 0.7.0'
  unittest: '>=0.11.0 <0.12.0'
  CspFix:
    git: https://github.com/sunglim/CspFixer.git
    version: '>=0.0.5'
